site_name: DeepEpiX
repo_url: https://github.com/agnesgrd/DeepEpiX
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            separate_signature: true
markdown_extensions:
  - admonition
  - pymdownx.superfences # nicer code blocks
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Overview: index.md
  - Installation: install.md
  - Architecture:
      - Folder Structure: folder-structure.md
      - App Structure: app-structure.md
      - Page Structure: page-structure.md
  - User Guide:
      - Load & Preprocess Data: user/dataset.md
      - Create Sensors Layout: user/montage.md
      - Visualize Preprocessed Signal: user/raw-viz.md
      - Analyze Preprocessed Signal: user/raw-analyze.md
      - Save Modifications: user/save.md
      - Visualize ICA: user/ica-viz.md
      - Add your own model: user/new-model.md
  - Developer Guide:
      - Setup & run: dev/setup.md
      - Add a new page: dev/new_page.md
      - Run external scripts: dev/subprocess.md
      - Write a callback: dev/callback.md
      - Useful layout: dev/layout.md
      - Style guide: dev/style.md
  - Pages:
      - Preprocessing tab: pages/preprocessing.md
      - PSD tab: pages/psd.md
  - Callbacks:
      - Overview: callbacks/index.md
      - Frequency controls: callbacks/frequency.md
